# Generated by Django 4.2.3 on 2023-07-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
