# Generated by Django 4.2.3 on 2023-07-25 11:23

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': [django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('vote_total'), '*', models.Value(0.7)), '+', django.db.models.expressions.CombinedExpression(models.F('vote_ratio'), '*', models.Value(0.3))), '*', models.Value(-1)), 'title']},
        ),
    ]
